# Nigeria States and Capitals and their Slogans.

states = {"Abia State" : "Umuahia",
          "Adamawa State" : "Yola",
          "Akwa ibom State": "Uyo",
          "Anambra State" : "Awka",
          "Bayelsa State" : "Yenegoa",
          "Bauchi State" : "Bauchi",
          "Benue State" : "Makurdi",
          "Bornu State" : "Maiduguri",
          "Cross river  State" : "Calabar",
          "Delta State" : "Asaba",
          "Ebonyi State" : "Abakaliki",
          "Edo State" : "Benin",
          "Ekiti State" : "Ado ekiti",
          "Enugu State" : "Enugu",
          "Gombe State" : "Gombe",
          "Imo State" : "Owerri",
          "Jigawa State" : "Dutse",
          "Kaduna State" : "Kaduna",
          "Katsina State" : "Katsina",
          "Kano State" : "Kano",
          "Kebbi State" : "Benin kebbi",
          "Kogi State" : "Lokoja",
          "Kwara State" : "Ilorin", 
          "Lagos State" : "Ikeja",
          "Nassarawa State" : "Lafia"
          "Niger State"  "Minna",
          "Ogun State" : "Abeokuta",
          "Ondo State" : "Akure",
          "Osun State" : "Osogbo",
          "Oyo State" : "Ibadan",
          "Plateau State" : "Jos",
          "Rivers State" : "Port-Harcourt",
          "Sokoto State" : "Sokoto",
          "Taraba State" : "Jalingo",
          "Yobe State" : "Damaturu",
          "Zamfara State" : "Gusau",
          "FCT" : "ABUJA"}

slogan = {"Abia State" : "God's own state",
          "Adamawa State" : "Land of beauty", 
          "Akwa ibom State" : "Land of promise",
          "Anambra State" : "Light of the nation",
          "Bauchi State" : "Pearl of tourism",
          "Bayelsa State" : "Glory of all lands",
          "Benue State" : "Food basket of the nation",
          "Borno State" : "Home of peace",
          "Cross river State" : "The people's paradise",
          "Delta State" : "The big heart",
          "Ebonyi State" : "Salt of the nation",
          "Edo State" : "Heart beat of the nation",
          "Ekiti State" : "Land of honour and integrity",
          "Enugu State" : "Coal city state",
          "Gombe State" : "Jewel in the savannah",
          "Imo State" : "Eastern heart",
          "Jigawa State" : "The new world",
          "Kaduna State" : "Centre of learning",
          "Kano State" : "Centre of commerce",
          "Katsina State" : "Home of hospitality",
          "Kebbi State" : "Land of equity",
          "Kogi State" : "The confluence state",
          "Kwara State" : "State of harmony",
          "Lagos State" : "Centre of Excellence",
          "Nasarawa State" : "Home of solid minerals",
          "Niger State" : "The power state",
          "Ogun State" : "Gataway state",
          "Ondo State" : "Sunshine state",
          "Osun State" : "Land of virtue",
          "Oyo State" : "Pace setter state",
          "Plateau State" : "Home of peace and tourism",
          "Rivers State" : "Treasure base of the nation",
          "Sokoto State" : "Seat of the caliphate",
          "Taraba State" : "Nature's gift to the nation",
          "Yobe State" : "Pride of the sahel",
          "Zamfara State" : "Farming is our pride"}

print(states.keys())
print(states.values())

for keys, value in states.items():
    print(f"{keys} : {value}")

item = states.items()
print(item) 